#!/bin/bash
# ---- Apply Arping Wrapper ----
#
# UBIOS's ubios-udapi-server runs an `nl-neighbors-poll` subsystem that
# watches the kernel neighbor cache and calls `arping -I <bridge> <ip>`
# for every entry, on a short periodic cycle.  On an IXP peering fabric
# this produces a continuous broadcast ARP storm that violates IX
# policy (AMS-IX / SIX require 4-hour ARP cache timeout).
#
# There is no config switch to disable the behavior.  The surgical fix
# is to interpose a wrapper over /usr/sbin/arping that silently returns
# success (exit 0) when invoked on an IXP bridge, while still passing
# all other invocations through to the real binary.  The kernel's own
# NUD handles real reachability on the IXP via BGP dst_confirm(), so
# no functionality is lost.
#
# The wrapper is installed via bind-mount to avoid modifying the real
# /usr/sbin/arping — unmounting restores the original behavior.
#
# Config file format (one interface name per line, comments with #):
#   br3996
#   br3997
#   br3998
#   br3999
#
# Config resolution (first match wins):
#   1. Explicit argument:              $1
#   2. Per-host conf:                  conf/$(hostname).conf
#   3. Flat preferred:                 arping-wrapper.conf
#
# Usage:
#   apply-arping-wrapper.sh [config-path]
#   apply-arping-wrapper.sh --uninstall    # remove bind-mount only

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAPPER_DIR="/data/ix-arping-wrapper"
WRAPPER_BIN="${WRAPPER_DIR}/arping"
WRAPPER_REAL="${WRAPPER_DIR}/arping.real"
TARGET="/usr/sbin/arping"

# -----------------------------------------------------------------
# Uninstall mode — unmount the wrapper, restore original behavior
# -----------------------------------------------------------------
if [[ "${1:-}" == "--uninstall" ]]; then
    if mount | grep -q " on ${TARGET} "; then
        umount "${TARGET}"
        echo "[arping-wrapper] Unmounted wrapper from ${TARGET}"
    else
        echo "[arping-wrapper] No wrapper mount found at ${TARGET}"
    fi
    exit 0
fi

# -----------------------------------------------------------------
# Config resolution
# -----------------------------------------------------------------
if [[ -n "${1:-}" ]]; then
    CONF="$1"
elif [[ -f "${SCRIPT_DIR}/conf/$(hostname).conf" ]]; then
    CONF="${SCRIPT_DIR}/conf/$(hostname).conf"
elif [[ -f "${SCRIPT_DIR}/arping-wrapper.conf" ]]; then
    CONF="${SCRIPT_DIR}/arping-wrapper.conf"
else
    echo "[arping-wrapper] No config found for host '$(hostname)'."
    echo "                 Looked for:"
    echo "                   ${SCRIPT_DIR}/conf/$(hostname).conf"
    echo "                   ${SCRIPT_DIR}/arping-wrapper.conf"
    exit 1
fi

if [[ ! -f "${CONF}" ]]; then
    echo "[arping-wrapper] Config file not found: ${CONF}"
    exit 1
fi

# -----------------------------------------------------------------
# Parse config: strip comments, blank lines, and whitespace
# -----------------------------------------------------------------
INTERFACES=()
while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" ]] && continue
    INTERFACES+=("$line")
done < "${CONF}"

if [[ ${#INTERFACES[@]} -eq 0 ]]; then
    echo "[arping-wrapper] No interfaces in config: ${CONF}"
    exit 1
fi

echo "[arping-wrapper] Config: ${CONF}"
echo "[arping-wrapper] Interfaces to skip: ${INTERFACES[*]}"

# -----------------------------------------------------------------
# Build the wrapper case-pattern from the interface list
# -----------------------------------------------------------------
CASE_PATTERN=""
for iface in "${INTERFACES[@]}"; do
    if [[ -n "$CASE_PATTERN" ]]; then
        CASE_PATTERN+="|${iface}"
    else
        CASE_PATTERN="${iface}"
    fi
done

# -----------------------------------------------------------------
# Install the wrapper and its backup of the real binary
# -----------------------------------------------------------------
mkdir -p "${WRAPPER_DIR}"

# Copy the real binary (only if it's not already our wrapper and the
# backup doesn't exist yet) — the bind-mount makes ls see the wrapper,
# so we check via the mount table.
if ! mount | grep -q " on ${TARGET} "; then
    if [[ ! -f "${WRAPPER_REAL}" ]]; then
        cp "${TARGET}" "${WRAPPER_REAL}"
        echo "[arping-wrapper] Saved real binary: ${WRAPPER_REAL}"
    fi
fi

# Write (or refresh) the wrapper script.  We always rewrite so the
# interface list stays in sync with the config file.
cat > "${WRAPPER_BIN}" <<WRAPPER
#!/bin/bash
# Auto-generated by apply-arping-wrapper.sh — do not edit by hand.
# Interfaces skipped: ${INTERFACES[*]}
#
# We silently exit 0 for IX interfaces so ubios-udapi-server's
# nl-neighbors-poll believes its arping succeeded.  The kernel's own
# NUD handles real reachability via BGP dst_confirm().
args=("\$@")
for ((i=0; i<\${#args[@]}; i++)); do
    if [[ "\${args[i]}" == "-I" && \$((i+1)) -lt \${#args[@]} ]]; then
        case "\${args[i+1]}" in
            ${CASE_PATTERN}) exit 0 ;;
        esac
    fi
done
exec "${WRAPPER_REAL}" "\$@"
WRAPPER
chmod +x "${WRAPPER_BIN}"
echo "[arping-wrapper] Installed wrapper: ${WRAPPER_BIN}"

# -----------------------------------------------------------------
# Apply the bind-mount (idempotent — if already mounted, skip)
# -----------------------------------------------------------------
if mount | grep -q " on ${TARGET} "; then
    echo "[arping-wrapper] Wrapper already bind-mounted at ${TARGET}"
else
    mount --bind "${WRAPPER_BIN}" "${TARGET}"
    echo "[arping-wrapper] Bind-mounted ${WRAPPER_BIN} -> ${TARGET}"
fi

# -----------------------------------------------------------------
# Verify
# -----------------------------------------------------------------
if ! mount | grep -q " on ${TARGET} "; then
    echo "[arping-wrapper] ERROR: bind-mount did not take effect."
    exit 1
fi

size=$(stat -c %s "${TARGET}")
real_size=$(stat -c %s "${WRAPPER_REAL}" 2>/dev/null || echo "?")
echo "[arping-wrapper] ${TARGET} is now ${size} bytes (real binary is ${real_size})."
echo "[arping-wrapper] Active."
